config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :create, :show, :index, :edit, :update]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :author_id, :post_id, presence: true

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: 'Post',
    inverse_of: :comments

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'User',
    inverse_of: :comments

  belongs_to :parent_coment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: 'Comment',
    optional: true

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: 'Comment'

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author_id, presence: true
  validates :subs, presence: { message: "Choose at least one" }

  has_many :post_subs, inverse_of: :post, dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'User',
    inverse_of: :posts

  has_many :comments,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: 'Comment',
    inverse_of: :post,
    dependent: :destroy

end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :moderator_id, presence: true

has_many :post_subs, inverse_of: :sub, dependent: :destroy

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: 'User',
    inverse_of: :subs

  has_many :posts,
    through: :post_subs,
    source: :post

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Can't be blank" }
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: 'Sub',
    inverse_of: :moderator

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'Post'

  has_many :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'User',
    inverse_of: :author,
    dependent: :destroy

  def generate_random_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(:username => user_name)
    return user if user && user.is_password?(password)
    nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(pass)
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end

  def reset_session_token!
    self.session_token = generate_random_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= generate_random_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :is_logged_in?

  def current_user
    return nil if session[:session_token].nil?
    @current_user =  User.find_by(:session_token => session[:session_token])
  end

  def is_logged_in?
    return !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors6] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @post = @comment.post
    render :show
  end

  def comment_params
    params.require(:comment).permit(:author_id, :post_id, :content, :parent_comment_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user!, only: [:new, :create, :edit, :update]
  before_action :require_author!, only: [:edit, :update]

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors4] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @author = @post.author
    render :edit
  end

  def update
    @post = Post.update(params[:id], post_params)
    if @post
      redirect_to post_url(@post)
    else
      flash.now[:errors5] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    Post.destroy(params[:id])
    redirect_back fallback_location: subs_url
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end

  def require_author!
    post = Post.find(params[:id])
    author = post.author
    redirect_to post_url(post) if current_user != author
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:session][:username], params[:session][:password])
    if user
      login_user!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors1] = ["Invalid Username or Password"]
      render :new
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_user!, only: [:new, :edit, :create, :update]
  before_action :require_mod!, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def new
    @user = current_user
    @sub = Sub.new
    render :new
  end

  def create
    sub = Sub.new(sub_params)
    if sub.save
      redirect_to sub_url(sub)
    else
      flash.now[:errors2] = sub.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    sub = Sub.update(params[:id], sub_params)
    if sub
      redirect_to sub_url(sub)
    else
      flash.now[:errors3] = sub.errors.full_messages
      render :edit
    end
  end


  def require_mod!
    sub = Sub.find(params[:id])
    moderator = User.find(sub.moderator_id)
    redirect_to subs_url if current_user != moderator
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to new_session_url
    else
      flash.now[:errors] = ["Invalid Username or Password"]
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

app/views/comments/_comment.html.erb
<p>
  <a href="<%= user_url(comment.author) %>"><%= comment.author.username %>:</a> <a href="<%= comment_url(comment) %>"><%= comment.content %></a>
</p>

<ul>
  <% comment.child_comments.each do |child_comment| %>
  <li>
    <%= render("comments/comment", comment: child_comment) %>
  </li>
  <% end %>
</ul>

app/views/comments/new.html.erb
<%= flash[:errors6] %>

<h1>New Comment</h1>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">
  <label>Comment
    <textarea name="comment[content]" rows="1" cols="20"></textarea>
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>

app/views/comments/show.html.erb
<h4><%= @comment.content %></h4>

<ul>
  <% @comment.child_comments.each do |comment| %>
    <li><a href="#"><%= comment.author.username %>:</a> <%= comment.content %></li>
    <br>
  <% end %>
</ul>
<br>
<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">
  <label>Comment
    <textarea name="comment[content]" rows="1" cols="20"></textarea>
  </label>
  <input type="submit" value="Submit Comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if current_user %>
    <p><a href="<%= user_url(current_user) %>"><%= current_user.username %></a></p>
    <form action="<%= session_url %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Logout">
    </form>
  <% else %>
    <a href="<%= new_session_url %>">Login</a>
    <br>
    <a href="<%= new_user_url %>">Sign Up</a>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if action == 'edit' %>
  <% action_url = post_url %>
  <% submit_val = 'Edit Post' %>
<% else %>
  <% action_url = posts_url %>
  <% submit_val = 'Create Post' %>
<% end %>


<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if action == 'edit' %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">
  <label for="title">Title</label>
  <input type="text" name="post[title]" value="<%= post.title %>">
  <br>
  <label>Content
    <textarea name="post[content]" rows="1" cols="20"><%= post.content %></textarea>
  </label>
  <br>
  <label for="url">Link to anything</label>
  <input id="url" type="text" name="post[url]" value="<%= post.url %>">
  <br>
  
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if post.sub_ids.include?(sub.id) %>>
      <%= sub.title %>
    </label>
    <br>
  <% end %>
  <input type="submit" value="<%= submit_val %>">

</form>

app/views/posts/edit.html.erb
<%= flash[:errors5] %>

<h1>Edit <%= @post.title %></h1>

<%= render partial: 'form', locals: {action: 'edit', post: @post} %>

app/views/posts/new.html.erb
<%= flash[:errors4] %>

<h1>New Post</h1>

<%= render partial: 'form', locals: {action: 'new', post: @post} %>

app/views/posts/show.html.erb
<h1><%= @post.title %>'s show Page</h1>

<a href="<%= subs_url %>">Back to subs</a>
<br>

<% if current_user && current_user == @post.author %>
  <a href="<%= edit_post_url(@post) %>">Edit Post</a>
  <br>
<% end %>

<h3>By: <a href="<%= user_url(@post.author) %>"><%= @post.author.username %></a></h3>

<p><%= @post.content %></p>
<br>
<img src="<%= @post.url %>" alt="">
<br>
<p><a href="<%= @post.url %>"><%= @post.url %></a></p>
<br>
<ul>
<% @post.comments.each do |comment| %>
  <% if comment.parent_comment_id == nil %>
    <li>
        <%= render("comments/comment", comment: comment) %>
    </li>
  <% end %>
<% end %>
</ul>


<% if current_user %>
  <a href="<%= new_post_comment_url(@post) %>">Add New Comment</a>
<% end %>

app/views/shared/_form.html.erb
<% if type == 'user' %>
  <% action_url = users_url %>
  <% input_val = 'Sign Up' %>
<% else %>
  <% action_url = session_url %>
  <% input_val = 'Login' %>
<% end %>


<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <label for="username">Username</label>
  <input id="username" type="text" name="<%= type %>[username]">
  <br>
  <label for="password">Password</label>
  <input type="password" name="<%= type %>[password]" id="password">
  <br>
  <input type="submit" value="<%= input_val %>">
</form>

app/views/subs/_form.html.erb
<% if action == 'edit' %>
  <% action_url = sub_url(@sub) %>
  <% submit_val = "Edit Sub" %>
<% else %>
  <% action_url = subs_url %>
  <% submit_val = "Create Sub" %>
<% end %>


<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if action == 'edit' %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="sub[title]" value="">
  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">
  <label for="title">Title</label>
  <input id="title" type="text" name="sub[title]" value="<%= sub.title %>">
  <br>
  <label>Description
    <textarea name="sub[description]" rows="1" cols="20"><%= sub.description %></textarea>
  </label>
  <br>
  <input type="submit" value="<%= submit_val %>">

</form>

app/views/subs/edit.html.erb
<%= flash[:errors3] %>

<h1>Edit <%= @sub.title %></h1>

<%= render 'subs/form', action: 'edit', sub: @sub %>

app/views/subs/index.html.erb
<h1>All the Subs</h1>

<a href="<%= new_sub_url %>">Make a new sub</a>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %> [<%= sub.description.truncate_words(4) %>]</a>
      <% if current_user && current_user == sub.moderator %>
        <a href="<%= edit_sub_url(sub) %>">Edit</a>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<%= flash[:errors2] %>

<h1>Create New Sub</h1>

<%= render 'subs/form', action: 'new', sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %>'s Show Page</h1>

<p><%= @sub.description %></p>
<br>
<p><a href="<%= new_post_url %>">New Post</a></p>
<br>
<ul>
  <% @sub.posts.each do |post| %>
    <li>By: <a href="<%= user_url(post.author) %>"><%= post.author.username %></a></li>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
    <li><a href="<%= post_url(post) %>"><%= post.content %></a></li>
    <li><img src="<%= post.url %>" alt=""></li>
    <form action="<%= post_url(post) %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit"value="Delete">
    </form>
  <% end %>
</ul>
<br>
<a href="<%= subs_url %>">Back to Subs</a>

app/views/users/index.html.erb
<h1>All the Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><a href="<%= user_url(user) %>"><%= user.username %></a></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= flash[:errors] %>

<h1>New User</h1>

<%= render 'shared/form', type: 'user' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Show Page!</h1>

<a href="<%= users_url %>">Back to Users</a>
<br>
<a href="<%= new_sub_url %>">Make a new sub</a>
<br>
<a href="<%= subs_url %>">All Subs</a>